//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class BitacorasInventariosBodega
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public decimal Cantidad { get; set; }
        public string Observacion { get; set; }
        public int DetalleInventarioBodegaId { get; set; }
        public int EmpleadoId { get; set; }
        public Nullable<int> FacturaCompraId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        public virtual DetallesInventariosBodega DetallesInventariosBodega { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual FacturasCompra FacturasCompra { get; set; }
    }
}
