//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class Costo
    {
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaCosto { get; set; }
        public decimal Valor { get; set; }
        public bool PagoCaja { get; set; }
        public string NumeroFactura { get; set; }
        public int TipoCostoId { get; set; }
        public int EmpleadoId { get; set; }
        public int ProveedorId { get; set; }
        public int CajaId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        public virtual Caja Caja { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        public virtual TiposCosto TiposCosto { get; set; }
    }
}
