//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gcsofcom_sigec_resto : DbContext
    {
        public gcsofcom_sigec_resto()
            : base("name=gcsofcom_sigec_resto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abono> Abonos { get; set; }
        public virtual DbSet<Archivo> Archivos { get; set; }
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<BitacorasFactura> BitacorasFacturas { get; set; }
        public virtual DbSet<BitacorasInventario> BitacorasInventarios { get; set; }
        public virtual DbSet<BitacorasInventariosBodega> BitacorasInventariosBodegas { get; set; }
        public virtual DbSet<Bodega> Bodegas { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<Cargo> Cargos { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Cierre> Cierres { get; set; }
        public virtual DbSet<CierresMediosPago> CierresMediosPagos { get; set; }
        public virtual DbSet<Ciudade> Ciudades { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Configuracione> Configuraciones { get; set; }
        public virtual DbSet<Convenio> Convenios { get; set; }
        public virtual DbSet<Costo> Costos { get; set; }
        public virtual DbSet<Credito> Creditos { get; set; }
        public virtual DbSet<Departamento> Departamentos { get; set; }
        public virtual DbSet<DetallesInventariosBodega> DetallesInventariosBodegas { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<Empresa> Empresas { get; set; }
        public virtual DbSet<Estado> Estados { get; set; }
        public virtual DbSet<Factura> Facturas { get; set; }
        public virtual DbSet<FacturasCompra> FacturasCompras { get; set; }
        public virtual DbSet<FacturasComprasDetalle> FacturasComprasDetalles { get; set; }
        public virtual DbSet<FacturasComprasDetallesPago> FacturasComprasDetallesPagos { get; set; }
        public virtual DbSet<FacturasConvenio> FacturasConvenios { get; set; }
        public virtual DbSet<FacturasDetalle> FacturasDetalles { get; set; }
        public virtual DbSet<FacturasDetallesPago> FacturasDetallesPagoes { get; set; }
        public virtual DbSet<Formulario> Formularios { get; set; }
        public virtual DbSet<FormulariosRole> FormulariosRoles { get; set; }
        public virtual DbSet<Insumo> Insumos { get; set; }
        public virtual DbSet<InsumosProducto> InsumosProductos { get; set; }
        public virtual DbSet<InsumosProveedore> InsumosProveedores { get; set; }
        public virtual DbSet<Inventario> Inventarios { get; set; }
        public virtual DbSet<InventariosDetalle> InventariosDetalles { get; set; }
        public virtual DbSet<MacroCategoria> MacroCategorias { get; set; }
        public virtual DbSet<MediosPago> MediosPagos { get; set; }
        public virtual DbSet<Modulo> Modulos { get; set; }
        public virtual DbSet<Motivo> Motivos { get; set; }
        public virtual DbSet<NotasCredito> NotasCreditos { get; set; }
        public virtual DbSet<NotasCreditosDetalle> NotasCreditosDetalles { get; set; }
        public virtual DbSet<Notificacione> Notificaciones { get; set; }
        public virtual DbSet<NumeracionesFactura> NumeracionesFacturas { get; set; }
        public virtual DbSet<Pais> Paises { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TiposCosto> TiposCostos { get; set; }
        public virtual DbSet<TiposEstado> TiposEstados { get; set; }
        public virtual DbSet<UnidadesMedida> UnidadesMedidas { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<UsuariosRole> UsuariosRoles { get; set; }
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Salones> Salones { get; set; }
        public virtual DbSet<Zonas> Zonas { get; set; }
        public virtual DbSet<Mesas> Mesas { get; set; }
        public virtual DbSet<ImpresorasCategorias> ImpresorasCategorias { get; set; }
        public virtual DbSet<Impresoras> Impresoras { get; set; }
        public virtual DbSet<Propinas> Propinas { get; set; }
        public virtual DbSet<Ordenes> Ordenes { get; set; }
        public virtual DbSet<OrdenesDetalles> OrdenesDetalles { get; set; }
        public virtual DbSet<ModificacionesProductos> ModificacionesProductos { get; set; }
    }
}
