//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventariosDetalle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventariosDetalle()
        {
            this.DetallesInventariosBodegas = new HashSet<DetallesInventariosBodega>();
        }
    
        public int Id { get; set; }
        public decimal CantidadTotal { get; set; }
        public decimal CantidadUsada { get; set; }
        public decimal CantidadIngresada { get; set; }
        public decimal PrecioCosto { get; set; }
        public int InventarioId { get; set; }
        public int InsumoId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesInventariosBodega> DetallesInventariosBodegas { get; set; }
        public virtual Insumo Insumo { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
