//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasCredito()
        {
            this.NotasCreditosDetalles = new HashSet<NotasCreditosDetalle>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Concepto { get; set; }
        public string MetodoCredito { get; set; }
        public decimal Total { get; set; }
        public bool PagoCaja { get; set; }
        public int MotivoId { get; set; }
        public int EstadoId { get; set; }
        public int FacturaId { get; set; }
        public int EmpleadoId { get; set; }
        public int MedioPagoId { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual MediosPago MediosPago { get; set; }
        public virtual Motivo Motivo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasCreditosDetalle> NotasCreditosDetalles { get; set; }
    }
}
