//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesDetalles
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime FechaEntregado { get; set; }
        public bool Activo { get; set; }
        public System.DateTime CreateAt { get; set; }
        public Nullable<System.DateTime> UpdateAt { get; set; }
        public Nullable<System.DateTime> DeleteAt { get; set; }
    
        public virtual Ordenes Orden { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
